excluded:
  - Tests

disabled_rules:
  # I really like putting else one a new line in long guard statements.
  - statement_position

  # I prefer 2 new lines before a MARK.
  # TODO: Add a custom rule to enforce this.
  - trailing_whitespace
  - operator_whitespace

  # TODO: Remove this
  - function_parameter_count

# TODO: Change to 120
line_length: 260

# TODO: Remove
file_length: 500
