name: Canvas
options:
  bundleIdPrefix: com.usecanvas
  usesTabs: true
  indentWidth: 4
  tabWidth: 4
  xcodeVersion: 9.3
  deploymentTarget:
    iOS: 11.0
settings:
  base:
    CLANG_ENABLE_OBJC_WEAK: YES
    CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS: YES
    CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: YES
    SWIFT_INSTALL_OBJC_HEADER: NO
  configs:
    release:
      SWIFT_COMPILATION_MODE: wholemodule
      GCC_OPTIMIZATION_LEVEL: fast
include:
  - Canvas-iOS/Canvas-iOS.yml
  - CanvasCore/CanvasCore.yml
  - CanvasNative/CanvasNative.yml
  - CanvasText/CanvasText.yml
