name: Canvas
options:
  bundleIdPrefix: com.usecanvas
  usesTabs: true
  indentWidth: 4
  tabWidth: 4
  xcodeVersion: 9.2
include:
  - Canvas-iOS/Canvas-iOS.yml
  - CanvasCore/CanvasCore.yml
  - CanvasNative/CanvasNative.yml
  - CanvasText/CanvasText.yml
