name: Canvas
options:
  bundleIdPrefix: com.usecanvas
  usesTabs: true
  indentWidth: 4
  tabWidth: 4
  xcodeVersion: 9.2
include:
  - Canvas-iOS/project.yml
  - CanvasCore/project.yml
  - CanvasNative/project.yml
  - CanvasText/project.yml
